#! /bin/sh

# # # # # # # #
#  AUTOSTART  #
# # # # # # # #

pgrep -x sxhkd > /dev/null || sxhkd &

#pipewire &
#pipewire-pulse &
#pipewire-media-session &
#xsetroot -solid "#2C2E3D"
xsetroot -cursor_name left_ptr &
#xinput --set-prop 11 322 1
sh ~/.config/polybar/polybar.sh &
sxhkd &
picom -b &
setxkbmap -layout us,ir -option grp:rctrl_rshift_toggle &
nitrogen --restore &
dbus-launch dunst --config ~/.config/dunst/dunstrc &
lxpolkit &
numlockx on &
#nm-applet &

# # # # # #
#  BSPWM  #
# # # # # #

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width          2 
bspc config normal_border_color \#3c3836
bspc config active_border_color \#8ec07c
bspc config focused_border_color \#665c54
#bspc config top_padding          -5
bspc config window_gap            12
bspc config split_ratio           0.52
bspc config borderless_monocle    true
#bspc config single_monocle        true # smart-gaps 
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# rules
bspc rule -a gnome-calculator state=floating border=off
bspc rule -a Nitrogen state=floating
bspc rule -a firefox:Toolkit state=floating
bspc rule -a Firefox-esr:Toolkit state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a xdg-desktop-portal-gnome state=floating
bspc rule -a xdg-desktop-portal-gtk state=floating
