#! /bin/sh
#AUTOSTART
pgrep -x sxhkd > /dev/null || sxhkd &

#pipewire &
#pipewire-pulse &
#pipewire-media-session &
#xsetroot -solid "#2C2E3D" &
xsetroot -cursor_name left_ptr & 
nitrogen --restore &
dbus-launch dunst --config ~/.config/dunst/dunstrc &
numlockx on &
picom -b -f &
setxkbmap -layout us,ir -option grp:win_space_toggle &
sxhkd &
sh ~/.config/polybar/polybar.sh &
#BSPWM
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         1
bspc config normal_border_color \#92837400
bspc config active_border_color \#8ec07c
bspc config focused_border_color \#928374
bspc config window_gap          12
#bspc config top_padding 30
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
